
name: Build and Deploy ASP.NET Core app to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: CATTEST
  AZURE_WEBAPP_PACKAGE_PATH: "./GreenSchoolCAT/GreenSchoolCAT/bin/Release/net8.0/publish"
  DotNet_Version: "8.x"
  SOLUTION_PATH: ./GreenSchoolCAT/GreenSchoolCAT.sln
  API_PROJECT_PATH: "./GreenSchoolCAT/GreenSchoolCAT/GreenSchoolCAT.csproj"
  PUBLISH_DIR: "./GreenSchoolCAT/GreenSchoolCAT/bin/Release/net8.0/publish"
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DotNet_Version }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}
         - name: Check if package path exists
           run: ls -al ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}


  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
       - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
